## End-to-end Skicit-Learn Workflow

In [10]:
import pandas as pd
import numpy as np
heart_disease = pd.read_csv('data/heart-disease.csv')

In [3]:
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [ ]:
# train test split 

# x = features
X = heart_disease.drop('target', axis=1)

# y = target
y = heart_disease['target']

In [ ]:
# pilih model dan hyperparameters
# karena targetnya hanya punya 2 nilai, yaitu 0 dan 1, berarti model yang akan digunakan ada model klasifikasi
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier() # default hyperparameters

In [ ]:
# kasih data ke model (fitting)
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,  test_size=0.2) # 80% buat training, 20% buat test

In [9]:
clf.fit(X_train, y_train)

RandomForestClassifier()

In [11]:
# prediksi
y_preds = clf.predict(X_test)

In [12]:
# model evaluasi
clf.score(X_train, y_train)

1.0

In [13]:
clf.score(X_test, y_test)

0.7704918032786885

In [14]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.74      0.74      0.74        27
           1       0.79      0.79      0.79        34

    accuracy                           0.77        61
   macro avg       0.77      0.77      0.77        61
weighted avg       0.77      0.77      0.77        61

In [15]:
confusion_matrix(y_test, y_preds)

array([[20,  7],
       [ 7, 27]])

In [16]:
accuracy_score(y_test, y_preds)

0.7704918032786885

In [ ]:
# Improve model
np.random.seed(42)
for i in range(10, 100, 10):
    print(f'Modelling menggunakan {i} estimators...')
    clf = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Akurasi model saat test: {clf.score(X_test, y_test) * 100:.2f}%")
    print("")

Modelling menggunakan 10 estimators...
Akurasi model saat test: 77.05%

Modelling menggunakan 20 estimators...
Akurasi model saat test: 80.33%

Modelling menggunakan 30 estimators...
Akurasi model saat test: 78.69%

Modelling menggunakan 40 estimators...
Akurasi model saat test: 73.77%

Modelling menggunakan 50 estimators...
Akurasi model saat test: 77.05%

Modelling menggunakan 60 estimators...
Akurasi model saat test: 75.41%

Modelling menggunakan 70 estimators...
Akurasi model saat test: 78.69%

Modelling menggunakan 80 estimators...
Akurasi model saat test: 78.69%

Modelling menggunakan 90 estimators...
Akurasi model saat test: 81.97%

In [ ]:
# save model
import pickle
pickle.dump(clf, open('random_forest_model_1.pkl', 'wb'))

In [20]:
# load model
loaded_model = pickle.load(open('random_forest_model_1.pkl', 'rb'))
loaded_model.score(X_test, y_test)

0.819672131147541

## Data Preprocessing
Tiga poin utama yang harus dilakukan:
1. Data Splitting Split = data menjadi 2 bagian, yaitu features(`X`) dan labels/target(`y`).
2. Handle Missing Values = bisa di isi dengan nilai baru `fillna()` ataupun dihapus `dropna()`.
3. Feature Encoding = Ubah data yang sebelumnya non-numeric, menjadi numeric.

In [21]:
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [24]:
X = heart_disease.drop('target', axis=1)
y = heart_disease['target']

In [26]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [27]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((242, 13), (61, 13), (242,), (61,))

In [28]:
X.shape[0] * 0.8

242.4

### Memastikan bahwa semua data yang akan digunakan ber-tipe numerik

In [54]:
car_sales = pd.read_csv('data/scikit-learn-data/car-sales-extended.csv')

In [55]:
car_sales.head()

     Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

di kolom Make dan Colour bukan numerik, oleh karena itu kita encoding dulu supaya jadi numerik

In [34]:
# data splitting
# from sklearn.model_selection import train_test_split

X = car_sales.drop('Price', axis=1)
y = car_sales['Price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
# Membuat model machine learning (ini bakal error soalnya belum di-encoding)
from sklearn.ensemble import RandomForestRegressor # karena kali ini target-nya berupa numerik kontinu jadi harus pake model regresi

model = RandomForestRegressor()
model.fit(X_train, y_train)
model.score(X_test, y_test)

ValueError: could not convert string to float: 'Toyota'

In [46]:
# Ubah data kategorikal ke numerikal
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ['Make', 'Colour', 'Doors']
one_hot = OneHotEncoder()
transformer = ColumnTransformer([('one_hot', one_hot, categorical_features)], remainder='passthrough')
transformed_X = transformer.fit_transform(X)

In [44]:
X.head() # sebelum di-encoding

     Make Colour  Odometer (KM)  Doors
0   Honda  White          35431      4
1     BMW   Blue         192714      5
2   Honda  White          84714      4
3  Toyota  White         154365      4
4  Nissan   Blue         181577      3

In [47]:
pd.DataFrame(transformed_X).head() # setelah di-encoding

    0    1    2    3    4    5    6    7    8    9    10   11        12
0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0

In [48]:
np.random.seed(42)
# split pake data yang udah di encoding
X_train, X_test, y_train, y_test = train_test_split(transformed_X, y, train_size=0.2)
model.fit(X_train, y_train)

RandomForestRegressor()

In [49]:
model.score(X_test, y_test)

0.26160452087764263

### Kalo datanya ada missing values
1. Imputation = Isi data yang hilang
2. Hapus data yg hilang

In [65]:
car_sales_missing = pd.read_csv('data/scikit-learn-data/car-sales-extended-missing-data.csv')
car_sales_missing.head()

     Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [66]:
# cek missing value
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

#### Opsi 1: Fill Missing data pake pandas

In [71]:
car_sales_missing['Doors'].value_counts()

Doors
4.0    811
5.0     75
3.0     64
Name: count, dtype: int64

In [72]:
# Fill 'Make' Column
car_sales_missing['Make'] = car_sales_missing['Make'].fillna('Missing')

# Fill 'Colour' Column
car_sales_missing['Colour'] = car_sales_missing['Colour'].fillna('Missing')

# Fill 'Odometer (KM)' Column
car_sales_missing['Odometer (KM)'] = car_sales_missing['Odometer (KM)'].fillna(car_sales_missing['Odometer (KM)'].mean())

# Fill 'Doors' Column
car_sales_missing['Doors'] = car_sales_missing['Doors'].fillna(4)

In [74]:
car_sales_missing.isna().sum()

Make              0
Colour            0
Odometer (KM)     0
Doors             0
Price            50
dtype: int64

In [75]:
# Hapus baris yang missing valuenya di bagian target 'Price'
car_sales_missing.dropna(inplace=True)

In [76]:
car_sales_missing.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [77]:
X = car_sales_missing.drop('Price', axis=1)
y = car_sales_missing['Price']

In [78]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ['Make', 'Colour', 'Doors']
one_hot = OneHotEncoder()
transformer = ColumnTransformer([('one_hot', one_hot, categorical_features)], remainder='passthrough')

transformed_X = transformer.fit_transform(X)